# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-25 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourdest',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=63)),
                ('dinfo', models.CharField(max_length=255)),
                ('drealweather', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourjournal',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False)),
                ('jname', models.CharField(max_length=63)),
                ('jdescrip', models.CharField(max_length=255)),
                ('jcontent', models.TextField()),
                ('jtag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tourspot',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=63)),
                ('scover', models.CharField(max_length=255)),
                ('sinfo', models.TextField()),
                ('sdest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourctrl.Tourdest')),
            ],
        ),
        migrations.CreateModel(
            name='Tourtrip',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tcover', models.CharField(max_length=255)),
                ('tname', models.CharField(max_length=63)),
                ('tdescrip', models.CharField(max_length=255)),
                ('tdays', models.IntegerField()),
                ('tpeople', models.CharField(max_length=63)),
                ('ttrip', models.TextField()),
                ('tdest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourctrl.Tourdest')),
                ('tspot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourctrl.Tourspot')),
            ],
        ),
        migrations.CreateModel(
            name='Touruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uico', models.CharField(max_length=255, null=True)),
                ('usign', models.CharField(blank=True, max_length=31, null=True)),
                ('ulocation', models.CharField(blank=True, max_length=63, null=True)),
                ('ujointime', models.CharField(max_length=15)),
                ('utag', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tourjournal',
            name='juser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tourctrl.Touruser'),
        ),
    ]
