# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourctrl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourjournal',
            name='jcover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
